### ISSUE TITLE
PR follow-up commits strategy at odds with comment from rust-highfive bot

### ISSUE THREAD

**Issue by mightyiam** [rust-lang/rustc-dev-guide#900] opened 2020-09-29 07:49 UTC
https://github.com/rust-lang/rustc-dev-guide/blob/6b5c62c6f8946a1a158bb1e84e1dabe87daee820/src/contributing.md

Is this paragraph

> Rust follows a no merge-commit policy, meaning, when you encounter merge conflicts you are expected to always rebase instead of merging. E.g. always use rebase when bringing the latest changes from the master branch to your feature branch. Also, please make sure that fixup commits are squashed into other related commits with meaningful commit messages.

At odds with the bot comment https://github.com/rust-lang/rust/pull/77219#issuecomment-699454142 ?

> If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

**Comment by jyn514** [comment] 2020-09-30 14:22
The problem is that different reviewers have different preferences for how you handle git 😅 For example @Mark-Simulacrum prefers commits to be squashed, but I prefer extra commits so I don't have to worry about https://github.com/isaacs/github/issues/1834.

Maybe we could change it to say 'squash commits before it's merged'? I don't think there's a great universal guideline here.

**Comment by Mark-Simulacrum** [comment] 2020-09-30 14:29
I prefer the commits to be squashed mainly because I find it much easier to re-review PRs rather than trying to remember past state, usually because I go 1-2 weeks at least between reviews on a given PR and I need to figure out what was going on. It's much easier to do so when things are in a consistent state within each commit rather than fixup commits scattered in git history.

On small PRs, it's also true that I personally will not approve things with stray commits without them being squashed in, so if the author is constantly squashing we can save a cycle at the end.

**Comment by LeSeulArtichaut** [comment] 2020-09-30 14:30
I think squashing commits right before merging makes the most sense

**Comment by mightyiam** [comment] 2020-09-30 15:32
Is it OK if the commit strategy depends on the assigned reviewer?

**Comment by camelid** [comment] 2020-12-11 21:52
> I think squashing commits right before merging makes the most sense

Sometimes on larger PRs it's helpful to squash once or twice in the middle. E.g. I [had a PR](https://github.com/rust-lang/rust/issues/76934) that got up to 60 commits because we kept changing the approach, so it was helpful to squash before the final review.

**Comment by not-an-aardvark** [comment] 2021-02-17 00:57
Just ran into this in https://github.com/rust-lang/rustc-dev-guide/issues/1058. My two cents is that I don't have any strong opinions on squashing versus pushing new commits, but having two pieces of reference material give opposite guidelines is pretty confusing for new contributors, and that aspect can probably be fixed without needing to resolve the squashing-vs-pushing debate.

It seems like even removing both guidelines could be an improvement over the current state, because as a contributor I wouldn't end up worried that I was violating the "real" guidelines by picking the wrong advice to follow.

**Comment by rylev** [comment] 2021-02-17 09:12
I agree with @not-an-aardvark. If there is no actual agreed upon policy for what to do, we should not pretend there is.

**Comment by jhg** [comment] 2021-04-18 17:07
I agree with @not-an-aardvark. And maybe the squashing-vs-pushing debate will not be resolved. Some advantages and tradeoffs are hardly objectives and mainly preferences (how it looks, what is beautiful, how to use git, how much effort request to others to put on using git to contribute, etc). Will really that contribute to add value to Rust for the rest of people?

I think the important is to avoid to reject contributions based on only personal preferences, or something that we couldn't debate with something better than what each one like more when we can agree that changes are good. 😄 And somethings has the tradeoff of to need more experience or effort with git, but some people could prefer a simpler way. I prefer only request that to myself instead to others.

There is ways that maybe I like more to do something but it doesn't make strongly bad or to reject work from another developer. 😃

**Closed** 2021-06-24 16:50 UTC
