### ISSUE TITLE
Finish chapters on macro expansion?

### ISSUE THREAD

**Issue by alexreg** [rust-lang/rustc-dev-guide#122] opened 2018-05-05 17:44 UTC
Could we get someone to do this? I'm not sure who would be most appropriate. @jseyfried knows it better than most, but he's been absent lately.

**Comment by mark-i-m** [comment] 2018-05-06 18:47
I believe @petrochenkov and @nrc are also really knowledgeable about the hygiene parts.

**Comment by alexreg** [comment] 2018-05-06 19:45
Yep, you're right, @petrochenkov is for sure. Haven't interacted with @nrc about it, but I'll trust you on it!

**Comment by mark-i-m** [comment] 2018-05-08 17:48
@federicomenaquintero had also mentioned in #15 that they might try to write something.

**Comment by mark-i-m** [comment] 2020-04-25 18:12
I'm going to go ahead and close this as a duplicate of #15. But thanks for filing the issue @alexreg !

**Closed by mark-i-m** 2020-04-25 18:12 UTC
