### ISSUE TITLE
Rename `part-N-intro.md` to more concrete one?

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rustc-dev-guide#1148] opened 2021-06-23 06:18 UTC
Followup of #1147, we currently name some chapters' intro section as `part-N-intro.md` but it can cause misleading since the actual part numbers are different (e.g. https://rustc-dev-guide.rust-lang.org/part-2-intro.html is the third chapter now). I think we should rename them to more concrete ones, e.g. `high-level-architecture.md` to avoid confusion and future _breakage_.

**Comment by jyn514** [comment] 2021-07-05 03:10
Duplicate of https://github.com/rust-lang/rustc-dev-guide/issues/762.

**Closed by jyn514** 2021-07-05 03:10 UTC
