### ISSUE TITLE
Lack of `README.md` in `rust` repository inner crates.

### ISSUE THREAD

**Issue by popzxc** [rust-lang/rustc-dev-guide#474] opened 2019-10-18 05:56 UTC
**Remark:** this issue is more like a topic for discussion, than actual change request.

## Description

Currently, most of crates in the `rust` repository don't have a personal `README.md` file.

There is a [`rustc-guide`](https://rust-lang.github.io/rustc-guide/) intended for developers, but it doesn't expose the purpose and the core moments of libraries.

Thus, a new developer has to dig in by himself.

Example scenario: developer decides to improve something in the compiler. He finds the module responsible for the feature he wants to enhance, and... that's it. Now he have to understand the whole module before he will be able to start working on it.

My proposal is the following:

Add a `README.md` to each crate (of course, not all at the same time) which will contain the following information:

- Short overview of the purpose of the crate.
- Core entry points (e.g., exposed public interfaces).
- Short description of modules in the crate, if they are has significant logical meaning.
- Optionally: some hints for developing in this module.
- Optionally: list of persons who are responsible for this module, so developers will know who they should be requesting a review from.

With such a file, entry threshold will be much lower and (I believe) getting into `rust` development will become easier.

From my side, I can try to implement such a `README.md` for `libtest` (as I'm familiar with it).

**Comment by mark-i-m** [comment] 2019-10-21 13:32
Yep, I actually went around deleting readmes a while back. They were all extremely out of date. I think the info you are looking for should be largely in the documentation or in this guide.

@spastorino perhaps we could start some sort of commenting initiative that seeks to add comments to the source?

**Comment by spastorino** [comment] 2019-10-21 16:28
@mark-i-m yeah, I like the idea and there are a lot of things to do. It's important to have them clear and prioritized. I think we should develop a good high level plan on what we want to accomplish.

Maybe this is a topic for one of the next meetings?.

**Comment by popzxc** [comment] 2019-10-21 17:18
If help would be needed, feel free to involve me :)

**Comment by spastorino** [comment] 2019-10-21 20:23
> If help would be needed, feel free to involve me :)

maybe jump on Zulip https://rust-lang.zulipchat.com/#narrow/stream/196385-t-compiler.2Fwg-learning and we can talk there.

**Comment by rylev** [comment] 2021-07-04 11:10
Going to close this as it looks like there is not README's for the individual crates by design.

**Closed by rylev** 2021-07-04 11:10 UTC
